-- Create cities table - standalone reference table for Minnesota cities
-- Data sourced from MNUDA CACHE - cities.csv

-- ============================================================================
-- STEP 1: Create cities table
-- ============================================================================

CREATE TABLE public.cities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  population INTEGER NOT NULL,
  county TEXT NOT NULL, -- Can contain multiple counties separated by comma
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Ensure unique city names
  CONSTRAINT cities_name_unique UNIQUE (name)
);

-- ============================================================================
-- STEP 2: Create indexes
-- ============================================================================

CREATE INDEX idx_cities_name ON public.cities(name);
CREATE INDEX idx_cities_county ON public.cities(county);
CREATE INDEX idx_cities_population ON public.cities(population DESC);

-- ============================================================================
-- STEP 3: Create updated_at trigger
-- ============================================================================

CREATE TRIGGER update_cities_updated_at 
  BEFORE UPDATE ON public.cities 
  FOR EACH ROW 
  EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- STEP 4: Insert city data
-- ============================================================================

INSERT INTO public.cities (name, population, county) VALUES
('Minneapolis', 428579, 'Hennepin'),
('Saint Paul', 307465, 'Ramsey'),
('Rochester', 123624, 'Olmsted'),
('Bloomington', 88344, 'Hennepin'),
('Duluth', 87986, 'St. Louis'),
('Brooklyn Park', 82893, 'Hennepin'),
('Woodbury', 80596, 'Washington'),
('Plymouth', 78551, 'Hennepin'),
('Lakeville', 77971, 'Dakota'),
('Blaine', 75172, 'Anoka, Ramsey'),
('Maple Grove', 72739, 'Hennepin'),
('St. Cloud', 72145, 'Stearns, Benton, Sherburne'),
('Eagan', 67240, 'Dakota'),
('Burnsville', 64864, 'Dakota'),
('Coon Rapids', 63807, 'Anoka'),
('Eden Prairie', 62905, 'Hennepin'),
('Apple Valley', 55272, 'Dakota'),
('Edina', 53564, 'Hennepin'),
('Minnetonka', 52651, 'Hennepin'),
('St. Louis Park', 49899, 'Hennepin'),
('Shakopee', 48401, 'Scott'),
('Mankato', 46459, 'Blue Earth, Nicollet, Le Sueur'),
('Moorhead', 45726, 'Clay'),
('Cottage Grove', 42760, 'Washington'),
('Maplewood', 40142, 'Ramsey'),
('Richfield', 36491, 'Hennepin'),
('Inver Grove Heights', 36226, 'Dakota'),
('Roseville', 35637, 'Ramsey'),
('Andover', 33426, 'Anoka'),
('Savage', 32896, 'Scott'),
('Brooklyn Center', 31755, 'Hennepin'),
('Fridley', 30679, 'Anoka'),
('Rosemount', 30581, 'Dakota'),
('Oakdale', 30441, 'Washington'),
('Chaska', 30167, 'Carver'),
('Ramsey', 28999, 'Anoka'),
('Prior Lake', 28018, 'Scott'),
('Elk River', 27606, 'Sherburne'),
('Shoreview', 26939, 'Ramsey'),
('Austin', 26690, 'Mower'),
('Owatonna', 26626, 'Steele'),
('Winona', 26173, 'Winona'),
('Chanhassen', 25746, 'Carver, Hennepin'),
('Faribault', 24983, 'Rice'),
('Farmington', 24464, 'Dakota'),
('Otsego', 23875, 'Wright'),
('White Bear Lake', 23479, 'Ramsey, Washington'),
('Champlin', 23045, 'Hennepin'),
('Lino Lakes', 22774, 'Anoka'),
('Hastings', 22502, 'Dakota, Washington'),
('New Brighton', 22374, 'Ramsey'),
('Columbia Heights', 22358, 'Anoka'),
('Crystal', 22082, 'Hennepin'),
('West St. Paul', 21920, 'Dakota'),
('Willmar', 21892, 'Kandiyohi'),
('St. Michael', 21681, 'Wright'),
('Northfield', 21316, 'Rice, Dakota'),
('Golden Valley', 21263, 'Hennepin'),
('New Hope', 20745, 'Hennepin'),
('Forest Lake', 20700, 'Washington'),
('South St. Paul', 20590, 'Dakota'),
('Sartell', 19979, 'Stearns, Benton'),
('Hopkins', 19462, 'Hennepin'),
('Stillwater', 19386, 'Washington'),
('Albert Lea', 18159, 'Freeborn'),
('Anoka', 18068, 'Anoka'),
('Ham Lake', 16905, 'Anoka'),
('Red Wing', 16788, 'Goodhue'),
('Hugo', 16765, 'Washington'),
('Buffalo', 16736, 'Wright'),
('Hibbing', 15940, 'St. Louis'),
('Bemidji', 15733, 'Beltrami'),
('Monticello', 15482, 'Wright'),
('Alexandria', 14914, 'Douglas'),
('Hutchinson', 14708, 'McLeod'),
('Rogers', 14493, 'Hennepin'),
('Brainerd', 14400, 'Crow Wing'),
('Fergus Falls', 14258, 'Otter Tail'),
('Lake Elmo', 14161, 'Washington'),
('North Mankato', 14241, 'Nicollet, Blue Earth'),
('Marshall', 13996, 'Lyon'),
('Robbinsdale', 13993, 'Hennepin'),
('New Ulm', 13970, 'Brown'),
('Sauk Rapids', 13832, 'Benton'),
('Waconia', 13831, 'Carver'),
('Worthington', 13754, 'Nobles'),
('Vadnais Heights', 13108, 'Ramsey'),
('Big Lake', 12855, 'Sherburne'),
('Mounds View', 12841, 'Ramsey'),
('North St. Paul', 12644, 'Ramsey'),
('Cloquet', 12475, 'Carlton'),
('St. Peter', 12456, 'Nicollet'),
('East Bethel', 12288, 'Anoka'),
('North Branch', 12258, 'Chisago'),
('Victoria', 11937, 'Carver'),
('Mendota Heights', 11542, 'Dakota'),
('Grand Rapids', 11244, 'Itasca'),
('Cambridge', 10974, 'Isanti'),
('Dayton', 10744, 'Hennepin, Wright'),
('Little Canada', 10590, 'Ramsey'),
('Hermantown', 10265, 'St. Louis'),
('Fairmont', 10176, 'Martin'),
('Detroit Lakes', 10033, 'Becker'),
('St. Anthony', 9993, 'Hennepin, Ramsey'),
('Arden Hills', 9490, 'Ramsey'),
('Oak Grove', 9327, 'Anoka'),
('Little Falls', 9206, 'Morrison'),
('Baxter', 9186, 'Crow Wing'),
('Minnetrista', 9091, 'Hennepin'),
('Waseca', 9067, 'Waseca'),
('Mound', 9031, 'Hennepin'),
('East Grand Forks', 8915, 'Polk'),
('Thief River Falls', 8779, 'Pennington'),
('Albertville', 8555, 'Wright'),
('St. Francis', 8523, 'Anoka, Isanti'),
('Waite Park', 8504, 'Stearns'),
('Corcoran', 8378, 'Hennepin'),
('Virginia', 8267, 'St. Louis'),
('New Prague', 8235, 'Scott, Le Sueur'),
('Orono', 8228, 'Hennepin'),
('Mahtomedi', 8199, 'Washington'),
('Wyoming', 8173, 'Chisago'),
('Shorewood', 7557, 'Hennepin'),
('Delano', 7513, 'Wright'),
('Isanti', 7493, 'Isanti'),
('Belle Plaine', 7444, 'Scott'),
('Crookston', 7269, 'Polk'),
('Medina', 7209, 'Hennepin'),
('Kasson', 7207, 'Dodge'),
('Spring Lake Park', 7083, 'Anoka, Ramsey'),
('St. Joseph', 6992, 'Stearns'),
('Stewartville', 6919, 'Olmsted'),
('Jordan', 6831, 'Scott'),
('Carver', 6810, 'Carver'),
('Byron', 6809, 'Olmsted'),
('Zimmerman', 6772, 'Sherburne'),
('Litchfield', 6515, 'Meeker'),
('Chisago City', 5953, 'Chisago'),
('Glencoe', 5659, 'McLeod'),
('Credit River', 5589, 'Scott'),
('International Falls', 5498, 'Koochiching'),
('Newport', 5415, 'Washington'),
('St. Paul Park', 5381, 'Washington'),
('Princeton', 5329, 'Mille Lacs, Sherburne'),
('Lake City', 5306, 'Wabasha, Goodhue'),
('Montevideo', 5300, 'Chippewa'),
('La Crescent', 5257, 'Houston, Winona'),
('Becker', 5252, 'Sherburne'),
('North Oaks', 5232, 'Ramsey'),
('Elko New Market', 5193, 'Scott'),
('Morris', 5192, 'Stevens'),
('Lonsdale', 5066, 'Rice'),
('Redwood Falls', 5038, 'Redwood, Renville'),
('Lindstrom', 5026, 'Chisago'),
('Falcon Heights', 5002, 'Ramsey'),
('Circle Pines', 4944, 'Anoka'),
('Luverne', 4941, 'Rock'),
('Dilworth', 4811, 'Clay'),
('Windom', 4797, 'Cottonwood'),
('Rockford', 4796, 'Wright, Hennepin'),
('Watertown', 4774, 'Carver'),
('St. James', 4750, 'Watonwan'),
('Sauk Centre', 4682, 'Stearns'),
('Oak Park Heights', 4674, 'Washington'),
('Chisholm', 4667, 'St. Louis'),
('Nowthen', 4565, 'Anoka'),
('Park Rapids', 4381, 'Hubbard'),
('Stacy', 4378, 'Chisago'),
('Wadena', 4373, 'Wadena, Otter Tail'),
('Cold Spring', 4326, 'Stearns'),
('Wayzata', 4308, 'Hennepin'),
('Columbus', 4307, 'Anoka'),
('Le Sueur', 4230, 'Le Sueur, Nicollet, Sibley'),
('Hanover', 4229, 'Wright, Hennepin'),
('Cannon Falls', 4201, 'Goodhue'),
('Rice Lake', 4168, 'St. Louis'),
('Goodview', 4088, 'Winona'),
('St. Charles', 4057, 'Winona'),
('Pipestone', 4034, 'Pipestone'),
('Zumbrota', 4013, 'Goodhue'),
('Centerville', 3956, 'Anoka'),
('Scandia', 3951, 'Washington'),
('Grant', 3942, 'Washington'),
('Montrose', 3925, 'Wright'),
('Melrose', 3911, 'Stearns'),
('Pine Island', 3870, 'Goodhue, Olmsted'),
('Pine City', 3865, 'Pine'),
('Bayport', 3785, 'Washington'),
('Mora', 3779, 'Kanabec'),
('Norwood Young America', 3774, 'Carver'),
('St. Augusta', 3767, 'Stearns'),
('Deephaven', 3762, 'Hennepin'),
('Independence', 3710, 'Hennepin'),
('Long Prairie', 3710, 'Todd'),
('Perham', 3708, 'Otter Tail'),
('Montgomery', 3537, 'Le Sueur'),
('Plainview', 3498, 'Wabasha'),
('Sleepy Eye', 3489, 'Brown'),
('Annandale', 3487, 'Wright'),
('Two Harbors', 3456, 'Lake'),
('Eveleth', 3415, 'St. Louis'),
('Benson', 3414, 'Swift'),
('Rush City', 3353, 'Chisago'),
('Eagle Lake', 3333, 'Blue Earth'),
('Breckenridge', 3308, 'Wilkin'),
('Jackson', 3252, 'Jackson'),
('Ely', 3214, 'St. Louis'),
('Blue Earth', 3159, 'Faribault'),
('Proctor', 3076, 'St. Louis'),
('Staples', 3075, 'Todd, Wadena'),
('Empire', 3068, 'Dakota'),
('Lexington', 3062, 'Anoka'),
('Milaca', 3060, 'Mille Lacs'),
('Chatfield', 3023, 'Fillmore, Olmsted'),
('Moose Lake', 3003, 'Carlton'),
('Afton', 2949, 'Washington'),
('Dodge Center', 2939, 'Dodge'),
('Greenfield', 2908, 'Hennepin'),
('Albany', 2874, 'Stearns'),
('Mountain Iron', 2847, 'St. Louis'),
('Cokato', 2782, 'Wright'),
('Caledonia', 2767, 'Houston'),
('Barnesville', 2765, 'Clay'),
('Breezy Point', 2750, 'Crow Wing'),
('Cohasset', 2723, 'Itasca'),
('Roseau', 2699, 'Roseau'),
('Granite Falls', 2678, 'Yellow Medicine, Chippewa'),
('Foley', 2666, 'Benton'),
('Glenwood', 2657, 'Pope'),
('Wabasha', 2598, 'Wabasha'),
('Pelican Rapids', 2594, 'Otter Tail'),
('Paynesville', 2586, 'Stearns'),
('Mayer', 2534, 'Carver'),
('Le Center', 2528, 'Le Sueur'),
('Osseo', 2526, 'Hennepin'),
('Lake Crystal', 2485, 'Blue Earth'),
('Rockville', 2471, 'Stearns'),
('Sandstone', 2466, 'Pine'),
('Janesville', 2462, 'Waseca'),
('Pequot Lakes', 2462, 'Crow Wing'),
('Spring Valley', 2445, 'Fillmore'),
('Madelia', 2430, 'Watonwan'),
('Crosslake', 2412, 'Crow Wing'),
('Wells', 2401, 'Faribault'),
('Lauderdale', 2341, 'Ramsey'),
('Gaylord', 2334, 'Sibley'),
('Crosby', 2328, 'Crow Wing'),
('Arlington', 2314, 'Sibley'),
('Olivia', 2306, 'Renville'),
('Excelsior', 2296, 'Hennepin'),
('Hawley', 2274, 'Clay'),
('Howard Lake', 2247, 'Wright'),
('Waverly', 2241, 'Wright'),
('Clearwater', 2221, 'Wright, Stearns'),
('Winsted', 2221, 'McLeod'),
('Maple Lake', 2214, 'Wright'),
('Rice', 2207, 'Benton'),
('Aitkin', 2174, 'Aitkin'),
('St. Bonifacius', 2169, 'Hennepin'),
('Nisswa', 2156, 'Crow Wing'),
('Cologne', 2097, 'Carver'),
('Tracy', 2041, 'Lyon'),
('Oronoco', 2040, 'Olmsted'),
('Eyota', 2025, 'Olmsted'),
('Coleraine', 1995, 'Itasca'),
('Springfield', 1995, 'Brown'),
('Hoyt Lakes', 1988, 'St. Louis'),
('Warroad', 1983, 'Roseau'),
('Ortonville', 1970, 'Big Stone'),
('Slayton', 1967, 'Murray'),
('Mountain Lake', 1944, 'Cottonwood'),
('Blooming Prairie', 1938, 'Steele, Dodge'),
('Long Lake', 1937, 'Hennepin'),
('Hinckley', 1918, 'Pine'),
('Lester Prairie', 1895, 'McLeod'),
('Kenyon', 1872, 'Goodhue'),
('Rushford', 1852, 'Fillmore'),
('Dundas', 1806, 'Rice'),
('Rock Creek', 1778, 'Pine'),
('Braham', 1776, 'Isanti, Kanabec'),
('Silver Bay', 1776, 'Lake'),
('Waterville', 1763, 'Le Sueur'),
('Osakis', 1747, 'Douglas, Todd'),
('Avon', 1742, 'Stearns'),
('Lakefield', 1710, 'Jackson'),
('Ada', 1696, 'Norman'),
('Canby', 1664, 'Yellow Medicine'),
('Lakeland', 1664, 'Washington'),
('Gilbert', 1655, 'St. Louis'),
('Aurora', 1652, 'St. Louis'),
('Maple Plain', 1648, 'Hennepin'),
('Spring Park', 1641, 'Hennepin'),
('Mapleton', 1639, 'Blue Earth'),
('Warren', 1549, 'Marshall'),
('Tonka Bay', 1540, 'Hennepin'),
('Richmond', 1521, 'Stearns'),
('Dassel', 1520, 'Meeker'),
('Lewiston', 1512, 'Winona'),
('Madison', 1488, 'Lac qui Parle'),
('New York Mills', 1481, 'Otter Tail'),
('Pierz', 1461, 'Morrison'),
('Dawson', 1431, 'Lac qui Parle'),
('Starbuck', 1419, 'Pope'),
('Clara City', 1390, 'Chippewa'),
('Winnebago', 1381, 'Faribault'),
('Fosston', 1377, 'Polk'),
('Babbitt', 1370, 'St. Louis'),
('Glyndon', 1369, 'Clay'),
('Menahga', 1366, 'Wadena'),
('Medford', 1362, 'Steele'),
('Hayfield', 1361, 'Dodge'),
('Minneota', 1355, 'Lyon'),
('Appleton', 1352, 'Swift'),
('Medicine Lake', 1343, 'Hennepin'),
('Wheaton', 1334, 'Traverse'),
('Winthrop', 1332, 'Sibley'),
('Red Lake Falls', 1327, 'Red Lake'),
('Fulda', 1326, 'Murray'),
('New London', 1316, 'Kandiyohi'),
('Preston', 1316, 'Fillmore'),
('Madison Lake', 1314, 'Blue Earth'),
('Frazee', 1310, 'Becker'),
('Grand Marais', 1306, 'Cook'),
('Bagley', 1304, 'Clearwater'),
('Royalton', 1280, 'Morrison, Benton'),
('Elbow Lake', 1276, 'Grant'),
('Renville', 1271, 'Renville'),
('Goodhue', 1244, 'Goodhue'),
('Edgerton', 1231, 'Pipestone'),
('Fairfax', 1217, 'Renville'),
('Mahnomen', 1216, 'Mahnomen'),
('Shafer', 1203, 'Chisago'),
('Spring Grove', 1202, 'Houston'),
('Adrian', 1198, 'Nobles'),
('New Richland', 1189, 'Waseca'),
('Grand Meadow', 1155, 'Mower'),
('Dellwood', 1147, 'Washington'),
('East Gull Lake', 1147, 'Cass'),
('Cottonwood', 1146, 'Lyon'),
('Harris', 1142, 'Chisago'),
('Elgin', 1139, 'Wabasha'),
('Lake Shore', 1123, 'Cass'),
('Nicollet', 1114, 'Nicollet'),
('Mantorville', 1110, 'Dodge'),
('Wanamingo', 1109, 'Goodhue'),
('Tyler', 1102, 'Lincoln'),
('Spicer', 1099, 'Kandiyohi'),
('Atwater', 1098, 'Kandiyohi'),
('Truman', 1069, 'Martin'),
('Eden Valley', 1068, 'Meeker, Stearns'),
('Taylors Falls', 1056, 'Chisago'),
('Sherburn', 1050, 'Martin'),
('Harmony', 1030, 'Fillmore'),
('Parkers Prairie', 1029, 'Otter Tail'),
('Morristown', 1016, 'Rice'),
('Watkins', 1010, 'Meeker'),
('Lake St. Croix Beach', 1005, 'Washington'),
('Scanlon', 998, 'Carlton'),
('Hector', 994, 'Renville'),
('Henderson', 988, 'Sibley'),
('Bird Island', 986, 'Renville'),
('Walker', 982, 'Cass'),
('Houston', 970, 'Houston'),
('Le Roy', 970, 'Mower'),
('Keewatin', 968, 'Itasca'),
('Biwabik', 965, 'St. Louis'),
('Carlton', 962, 'Carlton'),
('Nashwauk', 961, 'Itasca'),
('Hilltop', 956, 'Anoka'),
('Buhl', 945, 'St. Louis'),
('Baudette', 935, 'Lake of the Woods'),
('Deer River', 930, 'Itasca'),
('Pine River', 925, 'Cass'),
('Kimball', 919, 'Stearns'),
('Battle Lake', 914, 'Otter Tail'),
('Morgan', 879, 'Redwood'),
('Mazeppa', 869, 'Wabasha'),
('Emily', 863, 'Crow Wing'),
('Henning', 857, 'Otter Tail'),
('Hancock', 856, 'Stevens'),
('Silver Lake', 855, 'McLeod'),
('Hallock', 853, 'Kittson'),
('Landfall', 843, 'Washington'),
('West Concord', 842, 'Dodge'),
('Birchwood Village', 838, 'Washington'),
('Onamia', 830, 'Mille Lacs'),
('Browerville', 829, 'Todd'),
('Stockton', 829, 'Winona'),
('Isle', 827, 'Mille Lacs'),
('Clarkfield', 820, 'Yellow Medicine'),
('Blackduck', 816, 'Beltrami'),
('Bovey', 813, 'Itasca'),
('St. Stephen', 812, 'Stearns'),
('Rushford Village', 799, 'Fillmore'),
('Raymond', 796, 'Kandiyohi, Chippewa'),
('Gibbon', 788, 'Sibley'),
('Kerkhoven', 783, 'Swift'),
('Lamberton', 781, 'Redwood'),
('Fertile', 780, 'Polk'),
('Lilydale', 779, 'Dakota'),
('Dover', 771, 'Olmsted'),
('Cleveland', 769, 'Le Sueur'),
('Elysian', 759, 'Le Sueur, Waseca'),
('Sebeka', 753, 'Wadena'),
('Holdingford', 746, 'Stearns'),
('Wabasso', 745, 'Redwood'),
('Belgrade', 742, 'Stearns'),
('Westbrook', 734, 'Cottonwood'),
('Walnut Grove', 733, 'Redwood'),
('Courtland', 724, 'Nicollet'),
('Ottertail', 721, 'Otter Tail'),
('Kasota', 718, 'Le Sueur'),
('St. Clair', 717, 'Blue Earth'),
('Hampton', 714, 'Dakota'),
('Lake Park', 714, 'Becker'),
('Greenwood', 713, 'Hennepin'),
('Lanesboro', 712, 'Fillmore'),
('Hoffman', 709, 'Grant'),
('Brownton', 706, 'McLeod'),
('Mabel', 705, 'Fillmore'),
('Adams', 700, 'Mower'),
('Twin Valley', 697, 'Norman'),
('Welcome', 695, 'Martin'),
('Green Isle', 694, 'Sibley'),
('Trimont', 689, 'Martin'),
('Motley', 686, 'Morrison, Cass'),
('Freeport', 685, 'Stearns'),
('Cass Lake', 683, 'Cass'),
('Clarks Grove', 682, 'Freeborn'),
('Rollingstone', 682, 'Winona'),
('Clear Lake', 679, 'Sherburne'),
('Lake Benton', 678, 'Lincoln'),
('Greenbush', 674, 'Roseau'),
('Karlstad', 671, 'Kittson'),
('La Prairie', 666, 'Itasca'),
('Hills', 665, 'Rock'),
('Clarissa', 661, 'Todd'),
('Minnesota Lake', 660, 'Faribault, Blue Earth'),
('Ellendale', 658, 'Steele'),
('Marine on St. Croix', 658, 'Washington'),
('Brownsdale', 648, 'Mower'),
('Brooten', 646, 'Stearns, Pope'),
('Taconite', 642, 'Itasca'),
('Buffalo Lake', 641, 'Renville'),
('Center City', 640, 'Chisago'),
('Grove City', 634, 'Meeker'),
('Hill City', 615, 'Aitkin'),
('Randall', 614, 'Morrison'),
('Barnum', 610, 'Carlton'),
('Loretto', 610, 'Hennepin'),
('Marble', 606, 'Itasca'),
('Hendricks', 603, 'Lincoln'),
('Sabin', 601, 'Clay'),
('Butterfield', 597, 'Watonwan'),
('Heron Lake', 592, 'Jackson'),
('Evansville', 587, 'Douglas'),
('Balaton', 585, 'Lyon'),
('McIntosh', 581, 'Polk'),
('Foreston', 579, 'Mille Lacs'),
('Jasper', 579, 'Pipestone, Rock'),
('Alden', 575, 'Freeborn'),
('Stephen', 574, 'Marshall'),
('Deerwood', 570, 'Crow Wing'),
('Audubon', 569, 'Becker'),
('Kandiyohi', 565, 'Kandiyohi'),
('Ironton', 564, 'Crow Wing'),
('Glenville', 558, 'Freeborn'),
('Racine', 558, 'Mower'),
('Halstad', 551, 'Norman'),
('Bertha', 548, 'Todd'),
('Hamburg', 548, 'Carver'),
('Brownsville', 545, 'Houston'),
('Elmore', 545, 'Faribault'),
('Good Thunder', 545, 'Blue Earth'),
('Eagle Bend', 543, 'Todd'),
('Ivanhoe', 542, 'Lincoln'),
('Ranier', 540, 'Koochiching'),
('Minnetonka Beach', 537, 'Hennepin'),
('Hokah', 535, 'Houston'),
('Pillager', 531, 'Cass'),
('Argyle', 529, 'Marshall'),
('Littlefork', 527, 'Koochiching'),
('Lyle', 526, 'Mower'),
('Sunfish Lake', 522, 'Dakota'),
('Cook', 520, 'St. Louis'),
('Floodwood', 517, 'St. Louis'),
('Franklin', 516, 'Renville'),
('Amboy', 515, 'Blue Earth'),
('Gem Lake', 515, 'Ramsey'),
('Verndale', 512, 'Wadena'),
('Willernie', 512, 'Washington'),
('Graceville', 511, 'Big Stone'),
('Prinsburg', 511, 'Kandiyohi'),
('Browns Valley', 505, 'Traverse'),
('Brandon', 500, 'Douglas'),
('Brewster', 500, 'Nobles'),
('Jenkins', 500, 'Crow Wing'),
('Claremont', 499, 'Dodge'),
('Geneva', 499, 'Freeborn'),
('Cosmos', 495, 'Meeker'),
('Sacred Heart', 494, 'Renville'),
('Ellsworth', 487, 'Nobles'),
('Kiester', 487, 'Faribault'),
('Rothsay', 487, 'Wilkin, Otter Tail'),
('Carlos', 486, 'Douglas'),
('Upsala', 481, 'Morrison'),
('Bethel', 480, 'Anoka'),
('Pennock', 480, 'Kandiyohi'),
('Ashby', 472, 'Grant'),
('Ulen', 472, 'Clay'),
('Stewart', 470, 'McLeod'),
('Lafayette', 469, 'Nicollet'),
('Clearbrook', 468, 'Clearwater'),
('Sturgeon Lake', 468, 'Pine'),
('Altura', 465, 'Winona'),
('Randolph', 458, 'Dakota'),
('Wrenshall', 454, 'Carlton'),
('Fifty Lakes', 449, 'Crow Wing'),
('New Germany', 448, 'Carver'),
('Danube', 447, 'Renville'),
('Miltona', 442, 'Douglas'),
('Lynd', 435, 'Lyon'),
('Wykoff', 430, 'Fillmore'),
('Vermillion', 429, 'Dakota'),
('Kellogg', 426, 'Wabasha'),
('Tower', 421, 'St. Louis'),
('Akeley', 418, 'Hubbard'),
('Badger', 417, 'Roseau'),
('Milan', 416, 'Chippewa'),
('New Auburn', 413, 'Sibley'),
('Chokio', 411, 'Stevens'),
('Oklee', 407, 'Red Lake'),
('Fountain', 406, 'Fillmore'),
('Bigfork', 403, 'Itasca'),
('Fisher', 403, 'Polk'),
('Rose Creek', 403, 'Mower'),
('Morton', 402, 'Renville'),
('Ogilvie', 400, 'Kanabec'),
('Waubun', 399, 'Mahnomen'),
('Remer', 397, 'Cass'),
('Willow River', 396, 'Pine'),
('Alvarado', 388, 'Marshall'),
('Erskine', 387, 'Polk'),
('Herman', 386, 'Grant'),
('Hanska', 385, 'Brown'),
('Nevis', 385, 'Hubbard'),
('Pine Springs', 384, 'Washington'),
('Ghent', 378, 'Lyon'),
('McGregor', 378, 'Aitkin'),
('Barrett', 377, 'Grant'),
('Woodland', 377, 'Hennepin'),
('Comfrey', 376, 'Brown, Cottonwood'),
('Wood Lake', 373, 'Yellow Medicine'),
('Clinton', 371, 'Big Stone'),
('New Munich', 367, 'Stearns'),
('Round Lake', 367, 'Nobles'),
('Rushmore', 364, 'Nobles'),
('Underwood', 363, 'Otter Tail'),
('Emmons', 360, 'Freeborn'),
('Vergas', 357, 'Otter Tail'),
('Russell', 356, 'Lyon'),
('Bricelyn', 350, 'Faribault'),
('Newfolden', 343, 'Marshall'),
('St. Marys Point', 342, 'Washington'),
('Lancaster', 340, 'Kittson'),
('Long Beach', 339, 'Pope'),
('Darwin', 338, 'Meeker'),
('Jeffers', 338, 'Cottonwood'),
('Garfield', 337, 'Douglas'),
('Swanville', 337, 'Morrison, Todd'),
('Lowry', 335, 'Pope'),
('Finlayson', 333, 'Pine'),
('Deer Creek', 332, 'Otter Tail'),
('Askov', 331, 'Pine'),
('Lakeland Shores', 330, 'Washington'),
('Cuyuna', 327, 'Crow Wing'),
('Wilmont', 326, 'Nobles'),
('Dexter', 325, 'Mower'),
('Plato', 325, 'McLeod'),
('Calumet', 324, 'Itasca'),
('Grey Eagle', 324, 'Todd'),
('St. Martin', 318, 'Stearns'),
('Sanborn', 318, 'Redwood'),
('Vernon Center', 315, 'Blue Earth'),
('Canton', 313, 'Fillmore'),
('Cyrus', 312, 'Pope'),
('Hartland', 311, 'Freeborn'),
('Buckman', 309, 'Morrison'),
('Maynard', 304, 'Chippewa'),
('Hollandale', 303, 'Freeborn'),
('Hackensack', 300, 'Cass'),
('Murdock', 298, 'Swift'),
('Ceylon', 295, 'Martin'),
('Middle River', 294, 'Marshall'),
('Dakota', 290, 'Winona'),
('Belview', 285, 'Redwood'),
('Hendrum', 282, 'Norman'),
('Skyline', 282, 'Blue Earth'),
('Granada', 281, 'Martin'),
('Nerstrand', 278, 'Rice'),
('Plummer', 273, 'Red Lake'),
('Beaver Creek', 272, 'Rock'),
('Bowlus', 271, 'Morrison'),
('Kensington', 270, 'Douglas'),
('Chandler', 269, 'Murray'),
('Vesta', 268, 'Redwood'),
('Backus', 266, 'Cass'),
('Gonvick', 266, 'Clearwater'),
('Utica', 266, 'Winona'),
('Wilton', 266, 'Beltrami'),
('Eitzen', 262, 'Houston'),
('Freeborn', 257, 'Freeborn'),
('St. Hilaire', 256, 'Pennington'),
('Milroy', 254, 'Redwood'),
('Hewitt', 250, 'Todd'),
('Hayward', 249, 'Freeborn'),
('Kelliher', 249, 'Beltrami'),
('Wahkon', 249, 'Mille Lacs'),
('Cromwell', 246, 'Carlton'),
('Lake Wilson', 245, 'Murray'),
('Lake Lillian', 243, 'Kandiyohi'),
('Pease', 243, 'Mille Lacs'),
('Climax', 241, 'Polk'),
('Oslo', 239, 'Marshall'),
('Hanley Falls', 238, 'Yellow Medicine'),
('Echo', 235, 'Yellow Medicine'),
('Peterson', 227, 'Fillmore'),
('Ostrander', 226, 'Fillmore'),
('Villard', 224, 'Pope'),
('Donnelly', 223, 'Stevens'),
('Gary', 223, 'Norman'),
('Pemberton', 222, 'Blue Earth'),
('Bigelow', 220, 'Nobles'),
('Elrosa', 219, 'Stearns'),
('Gilman', 219, 'Benton'),
('Dennison', 218, 'Goodhue, Rice'),
('Sobieski', 218, 'Morrison'),
('Northrop', 217, 'Martin'),
('Ruthton', 217, 'Pipestone'),
('Currie', 214, 'Murray'),
('Dalton', 214, 'Otter Tail'),
('Frost', 214, 'Faribault'),
('Storden', 214, 'Cottonwood'),
('Orr', 213, 'St. Louis'),
('Bluffton', 212, 'Otter Tail'),
('Rutledge', 212, 'Pine'),
('Flensburg', 210, 'Morrison'),
('Lewisville', 207, 'Watonwan'),
('Beardsley', 206, 'Big Stone'),
('Greenwald', 205, 'Stearns'),
('Lucan', 205, 'Redwood'),
('Ogema', 205, 'Becker'),
('Waldorf', 203, 'Waseca'),
('Hitterdal', 202, 'Clay'),
('Lismore', 202, 'Nobles'),
('Garrison', 201, 'Crow Wing'),
('Okabena', 201, 'Jackson'),
('Magnolia', 188, 'Rock'),
('Forada', 187, 'Douglas'),
('Kingston', 187, 'Meeker'),
('Meire Grove', 186, 'Stearns'),
('Mendota', 185, 'Dakota'),
('Warba', 184, 'Itasca'),
('Minnesota City', 183, 'Winona'),
('Nelson', 183, 'Douglas'),
('South Haven', 183, 'Wright'),
('Callaway', 180, 'Becker'),
('Tenstrike', 180, 'Beltrami'),
('Hardwick', 179, 'Rock'),
('Easton', 177, 'Faribault'),
('Bellechester', 175, 'Goodhue, Wabasha'),
('Shelly', 175, 'Norman'),
('Holland', 173, 'Pipestone'),
('Kettle River', 173, 'Carlton'),
('Watson', 173, 'Chippewa'),
('Winger', 172, 'Polk'),
('Big Falls', 171, 'Koochiching'),
('Grygla', 171, 'Marshall'),
('Dent', 170, 'Otter Tail'),
('Lake Bronson', 170, 'Kittson'),
('Delavan', 169, 'Faribault'),
('Felton', 169, 'Clay'),
('Palisade', 169, 'Aitkin'),
('Wright', 169, 'Carlton'),
('Waltham', 167, 'Mower'),
('Wendell', 167, 'Grant'),
('Kennedy', 166, 'Kittson'),
('Elizabeth', 165, 'Otter Tail'),
('Campbell', 164, 'Wilkin'),
('Iona', 164, 'Murray'),
('Winton', 163, 'St. Louis'),
('Porter', 162, 'Yellow Medicine'),
('Steen', 162, 'Rock'),
('Longville', 158, 'Cass'),
('Grasston', 157, 'Kanabec'),
('Roosevelt', 156, 'Roseau, Lake of the Woods'),
('Williams', 156, 'Lake of the Woods'),
('Northome', 154, 'Koochiching'),
('Zumbro Falls', 154, 'Wabasha'),
('Bena', 152, 'Cass'),
('Conger', 151, 'Freeborn'),
('Kilkenny', 151, 'Le Sueur'),
('Clements', 148, 'Redwood'),
('Mapleview', 148, 'Mower'),
('Kinney', 147, 'St. Louis'),
('Millville', 144, 'Wabasha'),
('Laporte', 142, 'Hubbard'),
('Bellingham', 141, 'Lac qui Parle'),
('Blomkest', 140, 'Kandiyohi'),
('Boyd', 140, 'Lac qui Parle'),
('Meadowlands', 140, 'St. Louis'),
('Shevlin', 139, 'Clearwater'),
('Coates', 136, 'Dakota'),
('Heidelberg', 135, 'Le Sueur'),
('Roscoe', 134, 'Stearns'),
('Bingham Lake', 133, 'Cottonwood'),
('Elkton', 132, 'Mower'),
('Erhard', 132, 'Otter Tail'),
('Miesville', 132, 'Dakota'),
('Taunton', 132, 'Lyon'),
('Brook Park', 131, 'Pine'),
('Twin Lakes', 130, 'Freeborn'),
('Hammond', 129, 'Wabasha'),
('Chickamaw Beach', 128, 'Cass'),
('Dunnell', 127, 'Martin'),
('Elba', 127, 'Winona'),
('Clontarf', 126, 'Swift'),
('Odin', 124, 'Watonwan'),
('Lastrup', 123, 'Morrison'),
('Ormsby', 123, 'Watonwan, Martin'),
('Beaver Bay', 122, 'Lake'),
('Burtrum', 122, 'Todd'),
('Harding', 122, 'Morrison'),
('Wolverton', 122, 'Wilkin'),
('Foxhome', 121, 'Wilkin'),
('Federal Dam', 119, 'Cass'),
('Brooks', 117, 'Red Lake'),
('Garvin', 117, 'Lyon'),
('Brookston', 116, 'St. Louis'),
('Marietta', 116, 'Lac qui Parle'),
('Elmdale', 115, 'Morrison'),
('Riverton', 115, 'Crow Wing'),
('Trommald', 113, 'Crow Wing'),
('Biscay', 111, 'McLeod'),
('Woodstock', 111, 'Pipestone'),
('Avoca', 108, 'Murray'),
('De Graff', 108, 'Swift'),
('Effie', 107, 'Itasca'),
('Goodridge', 107, 'Pennington'),
('Quamba', 107, 'Kanabec'),
('Iron Junction', 106, 'St. Louis'),
('Perley', 106, 'Norman'),
('Mentor', 103, 'Polk'),
('Odessa', 103, 'Big Stone'),
('McKinley', 102, 'St. Louis'),
('Squaw Lake', 102, 'Itasca'),
('Danvers', 100, 'Swift'),
('Trosky', 100, 'Pipestone'),
('Comstock', 99, 'Clay'),
('Millerville', 99, 'Douglas'),
('Minneiska', 97, 'Wabasha, Winona'),
('Alpha', 96, 'Jackson'),
('Sunburg', 95, 'Kandiyohi'),
('Alberta', 94, 'Stevens'),
('Borup', 93, 'Norman'),
('St. Anthony', 93, 'Stearns'),
('St. Leo', 91, 'Yellow Medicine'),
('West Union', 91, 'Todd'),
('Beltrami', 90, 'Polk'),
('Lengby', 89, 'Polk'),
('Georgetown', 87, 'Clay'),
('Holt', 87, 'Marshall'),
('Holloway', 86, 'Swift'),
('Arco', 85, 'Lincoln'),
('Revere', 85, 'Redwood'),
('Bejou', 83, 'Mahnomen'),
('Bruno', 83, 'Pine'),
('Darfur', 83, 'Watonwan'),
('Fort Ripley', 82, 'Crow Wing'),
('Nimrod', 82, 'Wadena'),
('Seaforth', 82, 'Redwood'),
('Turtle River', 82, 'Beltrami'),
('Bock', 80, 'Mille Lacs'),
('New Trier', 80, 'Dakota'),
('Dundee', 79, 'Nobles'),
('Zemple', 79, 'Itasca'),
('Nielsville', 78, 'Polk'),
('Viking', 78, 'Marshall'),
('Lake Henry', 77, 'Stearns'),
('Richville', 77, 'Otter Tail'),
('Kerrick', 76, 'Pine'),
('La Salle', 75, 'Watonwan'),
('Solway', 72, 'Beltrami'),
('Wanda', 72, 'Redwood'),
('Dumont', 71, 'Traverse'),
('Evan', 71, 'Brown'),
('Spring Hill', 71, 'Stearns'),
('Clitherall', 70, 'Otter Tail'),
('Genola', 70, 'Morrison'),
('Walters', 70, 'Faribault'),
('Whalan', 69, 'Fillmore'),
('Strandquist', 68, 'Marshall'),
('Taopi', 68, 'Mower'),
('Wolf Lake', 67, 'Becker'),
('Nassau', 66, 'Lac qui Parle'),
('Sargeant', 66, 'Mower'),
('Nashua', 64, 'Wilkin'),
('Kent', 63, 'Wilkin'),
('Manhattan Beach', 63, 'Crow Wing'),
('Tamarack', 61, 'Aitkin'),
('Tintah', 61, 'Traverse'),
('Henriette', 60, 'Pine'),
('Kenneth', 60, 'Rock'),
('Cedar Mills', 59, 'Meeker'),
('Vining', 59, 'Otter Tail'),
('Ihlen', 58, 'Pipestone'),
('St. Rosa', 58, 'Stearns'),
('Wilder', 57, 'Jackson'),
('Farwell', 56, 'Pope'),
('Halma', 56, 'Kittson'),
('Gully', 55, 'Polk'),
('Hadley', 55, 'Murray'),
('Hatfield', 54, 'Pipestone'),
('Dovray', 53, 'Murray'),
('Hazel Run', 53, 'Yellow Medicine'),
('Mizpah', 53, 'Koochiching'),
('Manchester', 52, 'Freeborn'),
('Leonidas', 51, 'St. Louis'),
('St. Vincent', 50, 'Kittson'),
('Myrtle', 49, 'Freeborn'),
('Norcross', 49, 'Grant'),
('Urbank', 48, 'Otter Tail'),
('Sedan', 46, 'Pope'),
('Westport', 46, 'Pope'),
('Delhi', 45, 'Redwood'),
('Leonard', 43, 'Clearwater'),
('McGrath', 41, 'Aitkin'),
('Regal', 40, 'Kandiyohi'),
('Denham', 39, 'Pine'),
('Humboldt', 39, 'Kittson'),
('Trail', 38, 'Polk'),
('Aldrich', 34, 'Wadena'),
('Cobden', 32, 'Brown'),
('Doran', 30, 'Wilkin'),
('Louisburg', 29, 'Lac qui Parle'),
('Strathcona', 28, 'Roseau'),
('Correll', 27, 'Big Stone'),
('Boy River', 24, 'Cass'),
('Johnson', 24, 'Big Stone'),
('Florence', 21, 'Lyon'),
('Hillman', 21, 'Morrison'),
('Donaldson', 17, 'Kittson'),
('Barry', 14, 'Big Stone'),
('Funkley', 12, 'Beltrami'),
('Kinbrae', 10, 'Nobles')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- STEP 5: Enable Row Level Security
-- ============================================================================

ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STEP 6: Create RLS Policies
-- ============================================================================

-- Policy: Anyone can read cities (public reference data)
CREATE POLICY "Anyone can read cities"
  ON public.cities
  FOR SELECT
  TO authenticated, anon
  USING (true);

-- Policy: Admins can insert cities
CREATE POLICY "Admins can insert cities"
  ON public.cities
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.accounts
      WHERE accounts.user_id = auth.uid()
      AND accounts.role = 'admin'
    )
  );

-- Policy: Admins can update cities
CREATE POLICY "Admins can update cities"
  ON public.cities
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.accounts
      WHERE accounts.user_id = auth.uid()
      AND accounts.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.accounts
      WHERE accounts.user_id = auth.uid()
      AND accounts.role = 'admin'
    )
  );

-- Policy: Admins can delete cities
CREATE POLICY "Admins can delete cities"
  ON public.cities
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.accounts
      WHERE accounts.user_id = auth.uid()
      AND accounts.role = 'admin'
    )
  );

-- ============================================================================
-- STEP 7: Grant permissions
-- ============================================================================

GRANT SELECT ON public.cities TO authenticated;
GRANT SELECT ON public.cities TO anon;
GRANT INSERT, UPDATE, DELETE ON public.cities TO authenticated;

-- ============================================================================
-- STEP 8: Add comments
-- ============================================================================

COMMENT ON TABLE public.cities IS 'Standalone reference table for Minnesota cities. Can be referenced by id from other tables.';
COMMENT ON COLUMN public.cities.id IS 'Unique city ID (UUID) - can be referenced by other tables';
COMMENT ON COLUMN public.cities.name IS 'City name';
COMMENT ON COLUMN public.cities.population IS 'City population';
COMMENT ON COLUMN public.cities.county IS 'County or counties (comma-separated if multiple) where the city is located';

