-- Create enums for negative credit items
-- These enums classify all types of negative items found on credit reports

-- ====================================================
-- ENUM: negative_item_type
-- ====================================================

CREATE TYPE negative_item_type AS ENUM (
  'LATE_PAYMENT',
  'COLLECTION',
  'CHARGE_OFF',
  'REPOSSESSION',
  'FORECLOSURE',
  'BANKRUPTCY',
  'PUBLIC_RECORD',
  'TAX_LIEN',
  'CIVIL_JUDGMENT',
  'SETTLEMENT',
  'DELINQUENCY',
  'DEROGATORY_TRADELINE',
  'CLOSED_BY_GRANTOR',
  'VOLUNTARY_SURRENDER',
  'PAID_CHARGE_OFF',
  'PAID_COLLECTION',
  'INQUIRY',
  'FRAUD_FLAG',
  'IDENTITY_FLAG'
);

-- ====================================================
-- ENUM: negative_item_subtype
-- ====================================================

CREATE TYPE negative_item_subtype AS ENUM (
  'LATE_30','LATE_60','LATE_90','LATE_120','LATE_150','LATE_180','LATE_180_PLUS',
  'PATTERN_LATE_PAYMENTS','ROLLING_LATES','MISSED_PAYMENT','SERIOUSLY_DELINQUENT',

  'UNPAID_COLLECTION','PAID_COLLECTION','SETTLED_COLLECTION','ASSIGNED_COLLECTION',
  'MEDICAL_COLLECTION','UTILITY_COLLECTION','TELECOM_COLLECTION','CREDIT_CARD_COLLECTION',
  'AUTO_DEFICIENCY_COLLECTION','RENTAL_COLLECTION','JUDGMENT_COLLECTION',
  'RETURNED_CHECK_COLLECTION','INSURANCE_COLLECTION','PARKING_COLLECTION',
  'GOVERNMENT_COLLECTION','STUDENT_LOAN_COLLECTION','FEDERAL_COLLECTION',

  'CHARGE_OFF_UNPAID','CHARGE_OFF_PAID','CHARGE_OFF_SETTLED','CHARGE_OFF_TRANSFERRED',
  'CHARGE_OFF_PURCHASED','CHARGE_OFF_PROFIT_LOSS','CHARGE_OFF_WITH_BALANCE',
  'CHARGE_OFF_SOLD',

  'REPO_INVOLUNTARY','REPO_VOLUNTARY','REPO_DEFICIENCY','REPO_AFTER_CHARGE_OFF',
  'REPO_AFTER_COLLECTION','REPO_SETTLED','REPO_PAID',

  'FORECLOSURE_COMPLETED','FORECLOSURE_STARTED','PRE_FORECLOSURE','DEED_IN_LIEU',
  'SHORT_SALE','FORECLOSURE_DEFICIENCY','FORECLOSURE_SETTLED','FORECLOSURE_CHARGE_OFF',

  'BANKRUPTCY_CH7','BANKRUPTCY_CH13','BANKRUPTCY_CH11','BANKRUPTCY_CH12',
  'BANKRUPTCY_DISCHARGED','BANKRUPTCY_DISMISSED','BANKRUPTCY_FILED',
  'ACCOUNT_INCLUDED_BANKRUPTCY',

  'PUBLIC_RECORD_CIVIL_JUDGMENT','PUBLIC_RECORD_TAX_LIEN','PUBLIC_RECORD_SATISFIED_LIEN',
  'PUBLIC_RECORD_EVICTION','PUBLIC_RECORD_CHILD_SUPPORT','PUBLIC_RECORD_WAGE_GARNISHMENT',

  'TAX_LIEN_UNPAID','TAX_LIEN_PAID','TAX_LIEN_RELEASED',

  'JUDGMENT_UNPAID','JUDGMENT_SATISFIED','JUDGMENT_EVICTION',

  'SETTLED_FOR_LESS','SETTLEMENT_ACCEPTED',

  'DELINQUENT_30','DELINQUENT_60','DELINQUENT_90','DELINQUENT_120','DELINQUENT_150',
  'DELINQUENT_180','DELINQUENT_ROLLING',

  'DEROGATORY_GENERIC','ADVERSE_ACCOUNT','NEGATIVE_ACCOUNT',

  'ACCOUNT_CLOSED_BY_GRANTOR','HARDSHIP_PROGRAM','PAYMENT_PLAN','PAYMENT_ARRANGEMENT',

  'VOLUNTARY_SURRENDER_AUTO','VOLUNTARY_SURRENDER_OTHER',

  'PAID_AFTER_CHARGE_OFF','PAID_AFTER_COLLECTION',

  'HARD_INQUIRY','UNAUTHORIZED_INQUIRY','AUTO_INQUIRY','CREDIT_CARD_INQUIRY',
  'MORTGAGE_INQUIRY','LOAN_INQUIRY','TELECOM_INQUIRY','UTILITY_INQUIRY',
  'RENTAL_INQUIRY','COLLECTION_INQUIRY',

  'FRAUD_ALERT','ACTIVE_DUTY_ALERT','CREDIT_FREEZE','IDENTITY_THEFT_FLAG',

  'ADDRESS_MISMATCH','NAME_VARIATION','SSN_VARIATION','EMPLOYMENT_MISMATCH'
);

-- ====================================================
-- ENUM: negative_item_status
-- ====================================================

CREATE TYPE negative_item_status AS ENUM (
  'DEROGATORY','ADVERSE','NEGATIVE','PAST_DUE','PAST_DUE_WITH_AMOUNT','PAST_DUE_NO_AMOUNT',
  'CHARGE_OFF','COLLECTION','SETTLED','SETTLED_LESS_THAN_FULL','PAID','PAID_IN_FULL',
  'PAID_DEROGATORY','PAID_COLLECTION','PAID_CHARGE_OFF','PAID_LATE','ACCOUNT_CLOSED',
  'CLOSED_BY_GRANTOR','REPOSSESSED','FORECLOSED','BANKRUPTCY_INCLUDED',
  'BANKRUPTCY_DISCHARGED','BANKRUPTCY_FILED','BANKRUPTCY_DISMISSED','DISPUTE',
  'DISPUTE_RESOLVED','CONSUMER_DISAGREES','REINVESTIGATION_IN_PROGRESS','TRANSFERRED',
  'SOLD','WRITTEN_OFF','PAYMENT_AFTER_CHARGE_OFF','PAYMENT_AFTER_COLLECTION',
  'DEFAULTED','SERIOUSLY_DELINQUENT','CHRONICALLY_DELINQUENT'
);

-- ====================================================
-- ENUM: compliance_violation_type
-- ====================================================

CREATE TYPE compliance_violation_type AS ENUM (
  'WRONG_DATE_OPENED','WRONG_DATE_REPORTED','WRONG_LAST_PAYMENT_DATE','WRONG_DOB',
  'WRONG_DOFD','REAGING','DUPLICATE_ACCOUNT','DUPLICATE_COLLECTION','INCORRECT_BALANCE',
  'INCORRECT_LIMIT','INCORRECT_PAYMENT_HISTORY','MISSING_ECOA_CODE',
  'MISSING_COMPLIANCE_CODE','MIXED_FILE','ILLEGAL_REINSERTION','REPORTING_AFTER_DISCHARGE',
  'ACCOUNT_SHOULD_BE_ZERO_BALANCE','PAST_7_YEAR_LIMIT','UNVERIFIABLE_INFORMATION',
  'NO_PERMISSIBLE_PURPOSE'
);

